spring.application.name=catalog-service
server.port=8081

spring.thymeleaf.cache=false

management.endpoints.web.exposure.include=health,info

spring.datasource.url=jdbc:postgresql://localhost:5432/webshop
spring.datasource.username=webshop
spring.datasource.password=webshop

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.org.flywaydb=DEBUG